server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: yaho
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh