server:
  port: 8001


# 파일명 yaho-dev.yml
# {application}-{profiles}.yml
spring:
  profiles:
    active: dev
  application:
    name: yaho
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh