on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Set yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/java/resources/application.yml
        env:
          spring.config.import: ${{ secrets.CONFIG_IP }}
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: docker build
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_REPO }} ./
          docker push ${{ secrets.DOCKER_REPO }}  
          
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
          
  deploy:
    name: CD with EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: EC2 Docker Run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        run: |
          docker rm -f ${{ secrets.DOCKER_REPO }}
          docker rmi ${{ secrets.DOCKER_REPO }}
          docker run -p 8088:8001 -d ${{ secrets.DOCKER_REPO }}

        
          
