on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Set yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.config.import: ${{ secrets.CONFIG_IP }}
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: docker build
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_REPO }} ./
          docker push ${{ secrets.DOCKER_REPO }}  
          
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
          
  deploy:
    name: CD with EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00"
    - name: Generate deployment directory
      run: |
        mkdir -p deploy
        cp Dockerrun.aws.json deploy/Dockerrun.aws.json
        cd deploy && zip -r deploy.zip .

    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: ${{ secrets.AWS_EB_ENV_NAME }}
        environment_name: ${{ secrets.AWS_EB_APP_NAME }}
        version_label: Yaho- ${{ steps.currunt-time.outputs.formattedTime }}
        region: ${{ secrets.AWS_DEFAULT_REGION }}
        deployment_package: deploy/deploy.zip
        wait_for_environment_recovery: 200
          
